# Generated by Django 4.1.5 on 2024-11-29 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipe",
        ),
    ]
